// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Maximum_hls_Maximum_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-cpg238-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.277000,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=109,HLS_SYN_LUT=185,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module Maximum_hls (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        values_address0,
        values_ce0,
        values_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] values_address0;
output   values_ce0;
input  [31:0] values_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] values_address0;
reg values_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] max_reg_66;
wire    ap_CS_fsm_state2;
wire    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start;
wire    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_done;
wire    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_idle;
wire    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_ready;
wire   [1:0] grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_values_address0;
wire    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_values_ce0;
wire   [31:0] grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_max_2_out;
wire    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_max_2_out_ap_vld;
reg    grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] max_2_loc_fu_26;
wire    ap_CS_fsm_state5;
reg    values_ce0_local;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start_reg = 1'b0;
end

Maximum_hls_Maximum_hls_Pipeline_VITIS_LOOP_6_1 grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start),
    .ap_done(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_done),
    .ap_idle(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_idle),
    .ap_ready(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_ready),
    .max(max_reg_66),
    .values_address0(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_values_address0),
    .values_ce0(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_values_ce0),
    .values_q0(values_q0),
    .max_2_out(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_max_2_out),
    .max_2_out_ap_vld(grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_max_2_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_ready == 1'b1)) begin
            grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_max_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        max_2_loc_fu_26 <= grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_max_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        max_reg_66 <= values_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        values_address0 = grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_values_address0;
    end else begin
        values_address0 = 64'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        values_ce0 = grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_values_ce0;
    end else begin
        values_ce0 = values_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        values_ce0_local = 1'b1;
    end else begin
        values_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return = max_2_loc_fu_26;

assign grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start = grp_Maximum_hls_Pipeline_VITIS_LOOP_6_1_fu_44_ap_start_reg;

endmodule //Maximum_hls
